convert 1.png -quality 60% 1.jpg
convert 2.png -quality 60% 2.jpg
convert 3.png -quality 60% 3.jpg
convert 4.png -quality 60% 4.jpg
convert 5.png -quality 60% 5.jpg
convert 6.png -quality 60% 6.jpg
convert 7.png -quality 60% 7.jpg
convert 8.png -quality 60% 8.jpg
convert 9.png -quality 60% 9.jpg
convert bayrak.png -quality 60% bayrak.jpg
convert bosluk.png -quality 60% bosluk.jpg
convert cakbeslik.png -quality 60% cakbeslik.jpg
convert card.png -quality 60% card.jpg
convert cards.png -quality 60% cards.jpg
